SELECT DISTINCT(CITY) FROM STATION
WHERE NOT (
    SUBSTR(CITY, LENGTH(CITY), 1) = 'A' OR
    SUBSTR(CITY, LENGTH(CITY), 1) = 'I' OR
    SUBSTR(CITY, LENGTH(CITY), 1) = 'U' OR
    SUBSTR(CITY, LENGTH(CITY), 1) = 'E' OR
    SUBSTR(CITY, LENGTH(CITY), 1) = 'O'
) AND NOT (
    SUBSTR(CITY, 1, 1) = 'A' OR
    SUBSTR(CITY, 1, 1) = 'I' OR
    SUBSTR(CITY, 1, 1) = 'U' OR
    SUBSTR(CITY, 1, 1) = 'E' OR
    SUBSTR(CITY, 1, 1) = 'O'
);
